try {

} catch {
    error // podemos usarlo sin recibirlo en el catch
}